# Read up on pre-commit
# https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
#
exclude: .idea/

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: check-merge-conflict

- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
    - id: docformatter
      args: [
        -i,
        --wrap-summaries=120,
        --wrap-descriptions=120,
        --pre-summary-newline,
      ]

- repo: https://github.com/humitos/mirrors-autoflake
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
    - id: seed-isort-config

- repo: https://github.com/timothycrosley/isort
  rev: 5.6.4
  hooks:
  - id: isort

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
    - id: flake8
      additional_dependencies: [
        'pep8-naming',
        'flake8-comprehensions',
        'flake8-bugbear',
        'flake8-pytest-style',
        'flake8-variables-names',
        'flake8-class-attributes-order',
        'dlint',
      ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
    - id: mypy
      args: [--ignore-missing-imports, --check-untyped-defs, --disallow-incomplete-defs]
