# Read up on pre-commit
# https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
#
exclude: .idea/

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: check-merge-conflict

- repo: https://github.com/ambv/black
  rev: 22.8.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/myint/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
      args: [
        -i,
        --wrap-summaries=120,
        --wrap-descriptions=120,
        --pre-summary-newline,
      ]

- repo: https://github.com/humitos/mirrors-autoflake
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: isort (python)
  - id: isort
    name: isort (cython)
    types: [cython]
  - id: isort
    name: isort (pyi)
    types: [pyi]

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
      additional_dependencies: [
        'pep8-naming',
        'flake8-comprehensions',
        'flake8-bugbear',
        'flake8-pytest-style',
        'flake8-variables-names',
        'flake8-class-attributes-order',
        'dlint',
      ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
    - id: mypy
      args: [--config-file=mypy.cfg]
      additional_dependencies: [
        'types-cachetools',
        'types-pytz',
        'types-redis',
        'sqlalchemy[mypy]'
      ]
