name: Test in poetry envs

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            .venv
            ~/.poetry
            ~/.cache
          # TODO: this should use poetry.lock, but dephell is currently buggy
          key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}

      - name: Install poetry
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSL \
            "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py" | python

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          source "$HOME/.poetry/env"
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run checks
        run: |
          source "$HOME/.poetry/env"
          poetry run pytest tests/

      # Uncomment this lines if you wish to upload coverage to codecov:
      # https://codecov.io/
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     file: ./coverage.xml
